### ISSUE TITLE
frontend is not redeployed when custom domains are added

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#216]
I have a deployment in our `demo-sandbox1` AWS account which is exhibiting this issue. 

```yaml
version: 2
deployment:
  stackName: Granted-Chrisoktatesting2
  account: "616777145260"
  region: us-west-2
  release: v0.3.2
  parameters:
    FrontendDomain: oktatesting.granted.run
    FrontendCertificateARN: arn:aws:acm:us-east-1:616777145260:certificate/a0689f17-623a-4165-8f69-821cfcb91772
    CognitoDomainPrefix: granted-login-chrisoktatesting
    AdministratorGroupID: 00g6cyy2ha8VTk3mK5d7
    DeploymentSuffix: -chrisoktatesting
    IdentityProviderType: okta
    SamlSSOMetadataURL: https://dev-10612552.okta.com/app/exk6cyxole6hcJjym5d7/sso/saml/metadata
    ProviderConfiguration:
      aws-sso:
        uses: commonfate/aws-sso@v1
        with:
          identityStoreId: d-976708da7d
          instanceArn: arn:aws:sso:::instance/ssoins-825968feece9a0b6
          region: ap-southeast-2
    IdentityConfiguration:
      okta:
        apiToken: awsssm:///granted/secrets/identity/okta/token--chrisoktatesting:2
        orgUrl: https://dev-10612552.okta.com
```

Steps to reproduce:
1. Create a new Granted deployment with `gdeploy init`
2. Connect Granted to Okta SSO following our [docs](https://docs.commonfate.io/granted-approvals/sso/okta)
3. Set up a custom domain following our [docs](https://docs.commonfate.io/granted-approvals/configuration/custom-domain) (note: if you need DNS access there are some Route53 hosted zones set up in our dev account you can add DNS entries to)
4.  You will no longer be able to access the web UI - you'll see a page with a `redirect_mismatch` error similar to the below <img width="1392" alt="image" src="https://user-images.githubusercontent.com/17420369/187954895-24b65452-564a-4487-a9e9-ce815b4b2872.png">
