### ISSUE TITLE
aws-sso provider: if the SSO access role is restricted, only the permission sets which we have access to should be shown as options

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#230]
It is possible to restrict the SSO access role using the following CloudFormation:
```yaml
Resources:
  GrantedAccessHandlerSSORole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: "<ACCESS_HANDLER_EXECUTION_ROLE>"
        Version: "2012-10-17"
      Description: This role grants management access to AWS SSO for the Granted Access Handler.
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - sso:ListPermissionSets
                  - sso:ListTagsForResource
                  - sso:ListAccountAssignments
                  - organizations:ListAccounts
                  - organizations:DescribeAccount
                  - organizations:DescribeOrganization
                  - iam:GetSAMLProvider
                  - iam:GetRole
                  - iam:ListAttachedRolePolicies
                  - iam:ListRolePolicies
                  - identitystore:ListUsers
                Effect: Allow
                Resource: "*"
              - Action:
                  - sso:DescribeAccountAssignmentDeletionStatus
                  - sso:DescribeAccountAssignmentCreationStatus
                Effect: Allow
                Resource: "*"
              - Action:
                  - sso:CreateAccountAssignment
                  - sso:DeleteAccountAssignment
                  - sso:DescribePermissionSet
                Effect: Allow
                Resource:
                  - <SSO_INSTANCE_ARN>
                  - <PERMISSION_SET_ARN>
            Version: "2012-10-17"
          PolicyName: AccessHandlerSSOPolicy
Outputs:
  RoleARN:
    Value:
      Fn::GetAtt:
        - GrantedAccessHandlerSSORole
        - Arn
```

However, when this role is used, we get an AccessDeniedException when describing Permission Sets we don't have access to. We don't handle this and the provider hangs forever when trying to load options.
