### ISSUE TITLE
Updating a deployment to use Azure AD SSO causes a mismatch in Cognito client IDs

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#36]
To reproduce this issue:

1. deploy v0.1.2
    
    ```yaml
    version: 1
    deployment:
      stackName: Granted
      account: "0123456789012"
      region: us-west-2
      release: v0.1.2
      parameters:
        CognitoDomainPrefix: granted-login-cfdemocompany
        AdministratorGroupID: granted_administrators
    ```
    
2. update your deployment to our latest `main` commit
    
    ```yaml
    version: 1
    deployment:
      stackName: Granted
      account: "0123456789012"
      region: us-west-2
      release: https://granted-test-releases-us-west-2.s3.amazonaws.com/dev/21dc638f3570129654486264dbba6709440fe8e2/Granted.template.json
      parameters:
        CognitoDomainPrefix: granted-login-cfdemocompany
        AdministratorGroupID: granted_administrators
    ```

3. Add SSO by running `gdeploy sso configure` and [following our guide](https://docs.commonfate.io/granted-approvals/sso/azure/)
4. When trying to access the dashboard you will receive a Cognito error:

![Image](https://user-images.githubusercontent.com/17420369/179020477-b1566b73-b75d-41ae-b5e5-5d8eab6614ee.png)

Our CloudFormation deployment recreates a user pool, which causes the user pool ID to change. However, our dashboard uses the old user pool ID.
